In [78]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import StandardScaler

In [79]:
df= pd.read_csv("BEED_Data.csv")

In [80]:
df.head

<bound method NDFrame.head of        X1   X2   X3   X4   X5   X6  X7  X8  X9  X10  X11  X12  X13  X14  X15  \
0       4    7   18   25   28   27  20  10 -10  -18  -20  -16   13   32   12   
1      87  114  120  106   76   54  28   5 -19  -49  -85 -102 -100  -89  -61   
2    -131 -133 -140 -131 -123 -108 -58 -51 -70  -77  -76  -76  -73  -57  -40   
3      68  104   73   34  -12  -26 -38 -36 -67  -88  -25   31   18   -4    6   
4     -67  -90  -97  -94  -86  -71 -43 -11  23   46   58   50   39   19   -9   
...   ...  ...  ...  ...  ...  ...  ..  ..  ..  ...  ...  ...  ...  ...  ...   
7995   -9   -4   -7    2   -9  -14  -7  12  -5   -3   -2   -2  -12   -5    4   
7996   -8   -4   -7    1   -8  -14  -7  12  -6   -3   -2   -3  -15   -4    4   
7997   -6   -5   -7    1   -8  -14  -7  12  -7   -3   -2   -4  -16   -4    3   
7998   -5   -6   -6    1   -8  -13  -7  13  -7   -2   -3   -5  -15   -4    3   
7999   -4   -7   -5    2   -8  -12  -7  14  -6    0   -3   -6  -13   -4    2   

      X16

In [81]:
df.isnull().sum()

X1     0
X2     0
X3     0
X4     0
X5     0
X6     0
X7     0
X8     0
X9     0
X10    0
X11    0
X12    0
X13    0
X14    0
X15    0
X16    0
y      0
dtype: int64

In [82]:
Y= df[["y"]]
x= df[["X1", "X2","X3","X4","X5", "X6","X7","X8","X9","X10","X11","X12","X13","X14","X15","X16"]]

DECISIONTREECLASSIFIER

In [105]:
x_train, x_test, Y_train, Y_test= train_test_split(x, Y, test_size=0.3, random_state=42)
scaler= StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [107]:
Y_train = Y_train.values.ravel()
Y_test = Y_test.values.ravel()

In [108]:
treemodel = DecisionTreeClassifier(random_state=42)
treemodel.fit(x_train_scaled, Y_train)

DecisionTreeClassifier(random_state=42)

In [109]:
treeprediction = treemodel.predict(x_test_scaled)
treeprediction

array([1, 1, 0, ..., 0, 3, 3], shape=(2400,))

In [110]:
y_score=models.predict_proba(x_test_scaled)
roc_auc_score(Y_test, y_score, multi_class='ovr')

0.994396144667057

In [111]:
accuracy_score(Y_test, treeprediction)

0.8766666666666667

In [112]:
f1_score(Y_test, treeprediction, average='macro')

0.8750678176210684

In [113]:
y_score=treemodel.predict_proba(x_test_scaled)
roc_auc_score(Y_test, y_score, multi_class='ovr')

0.9169260173399473

LOGISTIC REGRESSION

In [114]:
x_train, x_test, Y_train, Y_test= train_test_split(x, Y, test_size=0.3, random_state=42)
scaler= StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)
model= LogisticRegression(max_iter=200)
model

LogisticRegression(max_iter=200)

In [115]:
Y_train = Y_train.values.ravel()
Y_test = Y_test.values.ravel()

In [116]:
model.fit(x_train_scaled, Y_train)

LogisticRegression(max_iter=200)

In [117]:
prediction= model.predict(x_test_scaled)
prediction

array([1, 3, 2, ..., 3, 1, 2], shape=(2400,))

In [118]:
accuracy_score(Y_test, prediction)

0.46125

In [119]:
f1_score(Y_test, prediction, average='macro')

0.4673927890095318

In [120]:
y_score=model.predict_proba(x_test_scaled)
roc_auc_score(Y_test, y_score, multi_class='ovr')

0.66162119762805

KNEIGHBOURSCLASSIFIER

In [100]:
x_train, x_test, Y_train, Y_test= train_test_split(x, Y, test_size=0.3, random_state=42)
scaler= StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

models = KNeighborsClassifier(n_neighbors=5)
models

KNeighborsClassifier()

In [122]:
Y_train = Y_train.ravel()
Y_test = Y_test.ravel()

In [123]:
models.fit(x_train_scaled, Y_train)

KNeighborsClassifier()

In [124]:
predictions= models.predict(x_test_scaled)
predictions

array([1, 1, 0, ..., 0, 3, 3], shape=(2400,))

In [125]:
accuracy_score(Y_test, predictions)

0.9595833333333333

In [126]:
f1_score(Y_test, predictions, average='macro')

0.9591183912031138